### ISSUE TITLE
Instaling by pip

### ISSUE THREAD

**Issue by raminsalmas** [autonlab/auton-survival#87]
Hi,

 pip install https://github.com/autonlab/auton-survival.git - doesn't work for me.

Looking for your advice.

Thanks.

**Comment by chiragnagpal** [comment]
Hi Ramin

Given that the package is currently developed primarily by research students without much bandwidth for propoer maintenance, we decided to not support pip installation, atleast for now.. this might change in the future depending on if we get enough extra hands to help with that. 

As of now, the best way to use `auton-survival` is to git clone the repo to your local machine and add the folder to your `PYTHONPATH`. this can be done somewhat easily by using  `sys`

> import sys
> sys.path.append(<FOLDER WITH AUTON-SURVIVAL>)

**Comment by AND2797** [comment]
If this is something of interest, I'm happy to take a crack at it?

**Comment by ecotner** [comment]
I have been testing this package out recently and was able to install it with pip by creating a `pyproject.toml` in the repo root directory so it could be installed using `setuptools`:
```toml
[project]
name = "auton_survival"
version = "1.0.0"
description = "the auton-survival package"
license = {file = "LICENSE"}
readme = "README.md"
dependencies = [
    "torch>=1.0.0",
    "numpy>=1.16.5",
    "pandas>=1.0.0",
    "tqdm>=4.0.0",
    "scikit-learn>=0.18",
    "torchvision>=0.7.0",
    "scikit-survival>=0.15.0",
    "lifelines>=0.26.4",
]

[build-system]
requires = [
    "setuptools",
    "wheel",
]

[tool.setuptools]
packages = ["auton_survival"]
```
Had no trouble installing and using things after that with `pip install -q -e ~/auton-survival`. With this approach you guys could get rid of your `requirements.txt` and just stick the dependencies in this file too. Here's some of the [relevant documentation](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html) if you're interested in learning more. Longer-term, I'd suggest you guys use a build tool like [poetry](https://python-poetry.org/) which manages dependencies, installations, and can even push to PyPI (so people can do pip installs without cloning the repo).

**Comment by matteo4diani** [comment]
@IvanUniTO citing from @ecotner 's comment:
> Longer-term, I'd suggest you guys use a build tool like [poetry](https://python-poetry.org/) which manages dependencies, installations, virtual environments, and can even push to PyPI **(so people can do pip installs without cloning the repo)**.

You are not bound to use poetry to manage your dependencies/envs, it's just our (proposed) build back-end. 
The final objective is to publish the package to PyPI and set up a robust CI-CD pipeline: `poetry` is the industry standard for this kind of job, other internal and external tools are sadly lagging behind in terms of features and documentation.

With the "poetry stuff" you can easily install via pip as a Version Control System dependency without having to `git clone` the repo every time, moreover the dependency will be updated automatically when you `pip install --upgrade`.

If you are interested in trying it out, `conda` can easily interface with pip and VCS dependencies, see [this StackOverflow thread](https://stackoverflow.com/questions/19042389/conda-installing-upgrading-directly-from-github).

Also, since you are referencing changes made in a PR, it would be better to comment on the PR with your opinions and suggestions or open a discussion: https://github.com/autonlab/auton-survival/pull/117 .

**Comment by matteo4diani** [comment]
@IvanUniTO No bother at all! I just want to ensure that all voices are heard since this is a scientific tool and users may prefer a different approach VS traditional SWE projects, thus why I invite you to speak out on the PR or here on this issue, and thanks for doing it btw.
I guess your stance on poetry proves my concern 😁

Regarding poetry breaking PEP standards, I see where you're coming from, and I strongly prefer the standards-oriented approach taken by [PDM](https://pdm.fming.dev/latest/), although it isn't mature yet to support a small team that wants to delegate the hard stuff away.
